# Generated by Django 4.0 on 2021-12-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(verbose_name='Длительность первой фазы')),
                ('second', models.IntegerField(verbose_name='Длительность второй фазы')),
                ('active', models.BooleanField(default=True, verbose_name='Голосование активно')),
                ('votes', models.IntegerField(default=0, verbose_name='Всего проголосовало')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Начало голосования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='FirstPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Время')),
                ('event', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Начало голосования')),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.timephase', verbose_name='Номер голосования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
