# Generated by Django 4.0 on 2022-01-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstphase',
            old_name='polls',
            new_name='vote',
        ),
    ]
